/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi_makelar;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sherlock
 */
public class FormBandar extends javax.swing.JFrame {

    /**
     * Creates new form FormPetani
     */
      
    private void ValidasiHuruf(KeyEvent a){
        if(Character.isDigit(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Masukan data dalam huruf");
        }
    }
    
    private void ValidasiAngka(KeyEvent b){
        if(Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,"Masukan data dalam angka");
        }
    }
private void kosongkan_form(){
         txtId.setText(null);
         txtNama.setText(null);
         txtPonsel.setText(null);
         txtCari.setText(null);
     }

private void tampilkan_data(){
DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("ID Bandar");
        model.addColumn("Nama Bandar");
        model.addColumn("No Ponsel");
        
        try {
            int no=1;
            String cari = txtCari.getText();
            String sql = "select * from bandar where nama_bandar like '%"+cari+"%' order by id_bandar desc";
            Connection conn=(Connection)koneksi.getKoneksi();
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3)});
            }
            tabelBandar.setModel(model);
        } catch (Exception e) {
        }

        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnKembali.setEnabled(true);
}
       
   private void AutoNumber(){
         try{
          String sql = "SELECT MAX(RIGHT(id_bandar,3)) AS no_auto FROM bandar";
          Connection conn = (Connection)koneksi.getKoneksi();
          Statement stm= conn.createStatement(); 
          ResultSet res = stm.executeQuery(sql);
            while(res.next()){         
           if (res.first()==false){
               txtId.setText("BDR001");
           }else{
               res.last();
               int set_kode = res.getInt(1)+1;
               String no_auto = String.valueOf(set_kode);
               int kode_next = no_auto.length();
               for (int a=0; a<3 - kode_next; a++){
                   no_auto ="0"+no_auto;
               }
               txtId.setText("BDR"+no_auto);
           }
           } 
         }catch (SQLException ex){
            Logger.getLogger(FormBandar.class.getName()).log(Level.SEVERE, null, ex);
          
    
     }
   }
   
    public FormBandar() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
        AutoNumber();
        txtId.setEnabled(false);
        txtNama.requestFocus();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBandar = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPonsel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Bandar");
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1120, 680));
        setSize(new java.awt.Dimension(1120, 680));

        jPanel1.setBackground(new java.awt.Color(52, 53, 57));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/manager (Custom) (1).png"))); // NOI18N
        jLabel1.setText("INPUT DATA BANDAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Nama Bandar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 130, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Masukkan Nama Bandar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 150, 30));

        txtId.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 295, 30));

        txtCari.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 290, 30));

        btnEdit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editt.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 100, 30));

        btnHapus.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 100, 30));

        btnKosong.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnKosong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kosong (Custom).png"))); // NOI18N
        btnKosong.setText("Kosongkan Form");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });
        jPanel1.add(btnKosong, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 160, 30));

        btnKembali.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(51, 51, 51));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kembali.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 140, 40));

        tabelBandar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tabelBandar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBandarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBandar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 860, 270));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("ID Bandar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 130, 30));

        btnHelp.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/help.png"))); // NOI18N
        btnHelp.setText("Bantuan");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 550, 140, -1));

        txtNama.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 295, 30));

        btnSimpan.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("No Ponsel");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 130, 30));

        txtPonsel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtPonsel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPonselKeyTyped(evt);
            }
        });
        jPanel1.add(txtPonsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 295, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("DATA BANDAR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg3 (Custom).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 940, 603));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Open (Custom) (2).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        String IdBandar = txtId.getText();
        String NamaBandar = txtNama.getText();
        String NoPonsel = txtPonsel.getText();
        

        if (IdBandar.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Id Bandar tidak boleh kosong");
            txtId.requestFocus();
        }else if (NamaBandar.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama Bandar tidak boleh kosong");
            txtNama.requestFocus();
        }else if (NoPonsel.isEmpty()) {
            JOptionPane.showMessageDialog(null,"No Ponsel tidak boleh kosong");
            txtPonsel.requestFocus();
        }else{
            try{
                Connection conn=(Connection)koneksi.getKoneksi();
                Statement stm=conn.createStatement();
               
                stm.executeUpdate("insert into bandar VALUES('"+IdBandar+"','"+NamaBandar+"','"+NoPonsel+"')");
                
                tampilkan_data();
                kosongkan_form();
                AutoNumber();
       
                 JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
        kosongkan_form(); 
        txtNama.requestFocus();
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnKembali.setEnabled(true);
        AutoNumber();
        tampilkan_data();
    }//GEN-LAST:event_btnKosongActionPerformed

    private void tabelBandarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBandarMouseClicked
        int baris = tabelBandar.rowAtPoint(evt.getPoint());
        String id =tabelBandar.getValueAt(baris, 1).toString();
        txtId.setText(id);
        String nama =tabelBandar.getValueAt(baris, 2).toString();
        txtNama.setText(nama);
        String hp = tabelBandar.getValueAt(baris,3).toString();
        txtPonsel.setText(hp);
        
        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        btnKembali.setEnabled(true);       // TODO add your handling code here:
    }//GEN-LAST:event_tabelBandarMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    String IdBandar = txtId.getText();
        String NamaBandar = txtNama.getText();
        String NoPonsel = txtPonsel.getText();
        

        if (IdBandar.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Id Bandar tidak boleh kosong");
            txtId.requestFocus();
        }else if (NamaBandar.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama Bandar tidak boleh kosong");
            txtNama.requestFocus();
        }else if (NoPonsel.isEmpty()) {
            JOptionPane.showMessageDialog(null,"No Ponsel tidak boleh kosong");
            txtPonsel.requestFocus();
        }else{
            try{
                Connection conn=(Connection)koneksi.getKoneksi();
                Statement stm=conn.createStatement();
               
               stm.executeUpdate("UPDATE bandar SET nama_bandar='"+NamaBandar+"', no_ponsel='"+NoPonsel+"'WHERE id_bandar='"+IdBandar+"'");
                tampilkan_data();
                kosongkan_form();
                AutoNumber();
     
       
                 JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
     String IdBandar=txtId.getText();

        if (IdBandar.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"ID Bandar tidak boleh kosong");
            txtId.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection conn=(Connection)koneksi.getKoneksi();
            Statement stm=conn.createStatement();
            stm.executeUpdate("DELETE FROM bandar WHERE id_bandar='"+IdBandar+"'");
            kosongkan_form();
            tampilkan_data();
            AutoNumber();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
            this.dispose();
            new MenuUtama().setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        tampilkan_data();
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
        ValidasiHuruf(evt);
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtPonselKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPonselKeyTyped
        // TODO add your handling code here:
        ValidasiAngka(evt);
    }//GEN-LAST:event_txtPonselKeyTyped

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Form Data Bandar"
            + "\nMenyimpan"
            + "\n1. Masukkan Nama Bandar"
            + "\n2. Masukkan No Ponsel"
            + "\n3. Klik Tombol Simpan"
            + "\n\nMengedit"
            + "\n1. Klik data yang akan di edit di tabel bandar"
            + "\n2. Rubah data yang akan di edit Nama Bandar/No Ponsel sesuai yang diinginkan"
            + "\n3. Klik Tombol Edit"
            + "\n\nMenghapus"
            + "\n1. Klik data yang akan di hapus di tabel bandar"
            + "\n2. Klik tombol hapus"
            + "\n3. Pesan peringatan akan muncul, klik OK jika sudah yakin data akan dihapus ", "Bantuan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBandar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKosong;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBandar;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPonsel;
    // End of variables declaration//GEN-END:variables
}
