/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi_makelar;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.Timer;

/**
 *
 * @author Sherlock
 */
public class Loading extends javax.swing.JFrame {
    private JFrame frame;
    private JPanel panel;
    private JProgressBar JP;
    

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadingBar.setStringPainted(true);
        Loading();
    }
    
    ActionListener waktu = new ActionListener(){
            public void actionPerformed(ActionEvent e){
            loadingBar.setValue(loadingBar.getValue()+1);
                if (loadingBar.getValue()==loadingBar.getMaximum()){
                    jalan.stop();
                    dispose();
                    new Login().setVisible(true);
                }if (loadingBar.getValue()==10){
                    loadingLabel.setText("Loading .");
                }if (loadingBar.getValue()==20){
                    loadingLabel.setText("Loading . .");
                }if (loadingBar.getValue()==30){
                    loadingLabel.setText("Loading . . .");
                }if (loadingBar.getValue()==40){
                    loadingLabel.setText("Loading . .");
                }if (loadingBar.getValue()==50){
                    loadingLabel.setText("Loading .");
                }if (loadingBar.getValue()==60){
                    loadingLabel.setText("Loading");
                }if (loadingBar.getValue()==70){
                    loadingLabel.setText("Loading .");
                }if (loadingBar.getValue()==80){
                    loadingLabel.setText("Loading . .");
                }if (loadingBar.getValue()==90){
                    loadingLabel.setText("Loading . . .");
                }
            }
            };
    
    Timer jalan = new Timer(50, waktu);
    public void Loading(){
        jalan.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadingBar = new javax.swing.JProgressBar();
        loadingLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 288));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(560, 288));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(560, 330));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingBar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        loadingBar.setForeground(new java.awt.Color(65, 196, 178));
        jPanel1.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 560, 20));

        loadingLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        loadingLabel.setForeground(new java.awt.Color(250, 250, 250));
        loadingLabel.setText("Loading");
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 360, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/farm-footer (Custom).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 560, 100));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Makelar Milenial (Custom).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 220, 150));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/25369 (Custom).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingLabel;
    // End of variables declaration//GEN-END:variables
}
